/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as SoonRouteImport } from './routes/Soon'
import { Route as ShopRouteImport } from './routes/Shop'
import { Route as SearchRouteImport } from './routes/Search'
import { Route as ComingSoonRouteImport } from './routes/ComingSoon'
import { Route as AccountRouteImport } from './routes/Account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as PolicyTermsRouteImport } from './routes/policy/terms'
import { Route as PolicyShippingRouteImport } from './routes/policy/shipping'
import { Route as PolicyReturnsRouteImport } from './routes/policy/returns'
import { Route as PolicyAboutRouteImport } from './routes/policy/about'
import { Route as PolicySlugRouteImport } from './routes/policy.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const SoonRoute = SoonRouteImport.update({
  id: '/Soon',
  path: '/Soon',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/Shop',
  path: '/Shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/Search',
  path: '/Search',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/ComingSoon',
  path: '/ComingSoon',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/Account',
  path: '/Account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyTermsRoute = PolicyTermsRouteImport.update({
  id: '/policy/terms',
  path: '/policy/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyShippingRoute = PolicyShippingRouteImport.update({
  id: '/policy/shipping',
  path: '/policy/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyReturnsRoute = PolicyReturnsRouteImport.update({
  id: '/policy/returns',
  path: '/policy/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyAboutRoute = PolicyAboutRouteImport.update({
  id: '/policy/about',
  path: '/policy/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicySlugRoute = PolicySlugRouteImport.update({
  id: '/policy/$slug',
  path: '/policy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Account': typeof AccountRoute
  '/ComingSoon': typeof ComingSoonRoute
  '/Search': typeof SearchRoute
  '/Shop': typeof ShopRoute
  '/Soon': typeof SoonRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/success': typeof SuccessRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/policy/$slug': typeof PolicySlugRoute
  '/policy/about': typeof PolicyAboutRoute
  '/policy/returns': typeof PolicyReturnsRoute
  '/policy/shipping': typeof PolicyShippingRoute
  '/policy/terms': typeof PolicyTermsRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Account': typeof AccountRoute
  '/ComingSoon': typeof ComingSoonRoute
  '/Search': typeof SearchRoute
  '/Shop': typeof ShopRoute
  '/Soon': typeof SoonRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/success': typeof SuccessRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/policy/$slug': typeof PolicySlugRoute
  '/policy/about': typeof PolicyAboutRoute
  '/policy/returns': typeof PolicyReturnsRoute
  '/policy/shipping': typeof PolicyShippingRoute
  '/policy/terms': typeof PolicyTermsRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Account': typeof AccountRoute
  '/ComingSoon': typeof ComingSoonRoute
  '/Search': typeof SearchRoute
  '/Shop': typeof ShopRoute
  '/Soon': typeof SoonRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/success': typeof SuccessRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/policy/$slug': typeof PolicySlugRoute
  '/policy/about': typeof PolicyAboutRoute
  '/policy/returns': typeof PolicyReturnsRoute
  '/policy/shipping': typeof PolicyShippingRoute
  '/policy/terms': typeof PolicyTermsRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Account'
    | '/ComingSoon'
    | '/Search'
    | '/Shop'
    | '/Soon'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/sitemap.xml'
    | '/stores'
    | '/success'
    | '/track-order'
    | '/wishlist'
    | '/category/$slug'
    | '/policy/$slug'
    | '/policy/about'
    | '/policy/returns'
    | '/policy/shipping'
    | '/policy/terms'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Account'
    | '/ComingSoon'
    | '/Search'
    | '/Shop'
    | '/Soon'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/sitemap.xml'
    | '/stores'
    | '/success'
    | '/track-order'
    | '/wishlist'
    | '/category/$slug'
    | '/policy/$slug'
    | '/policy/about'
    | '/policy/returns'
    | '/policy/shipping'
    | '/policy/terms'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/Account'
    | '/ComingSoon'
    | '/Search'
    | '/Shop'
    | '/Soon'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/sitemap.xml'
    | '/stores'
    | '/success'
    | '/track-order'
    | '/wishlist'
    | '/category/$slug'
    | '/policy/$slug'
    | '/policy/about'
    | '/policy/returns'
    | '/policy/shipping'
    | '/policy/terms'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ComingSoonRoute: typeof ComingSoonRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRoute
  SoonRoute: typeof SoonRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoresRoute: typeof StoresRoute
  SuccessRoute: typeof SuccessRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WishlistRoute: typeof WishlistRoute
  CategorySlugRoute: typeof CategorySlugRoute
  PolicySlugRoute: typeof PolicySlugRoute
  PolicyAboutRoute: typeof PolicyAboutRoute
  PolicyReturnsRoute: typeof PolicyReturnsRoute
  PolicyShippingRoute: typeof PolicyShippingRoute
  PolicyTermsRoute: typeof PolicyTermsRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Soon': {
      id: '/Soon'
      path: '/Soon'
      fullPath: '/Soon'
      preLoaderRoute: typeof SoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Shop': {
      id: '/Shop'
      path: '/Shop'
      fullPath: '/Shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Search': {
      id: '/Search'
      path: '/Search'
      fullPath: '/Search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ComingSoon': {
      id: '/ComingSoon'
      path: '/ComingSoon'
      fullPath: '/ComingSoon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Account': {
      id: '/Account'
      path: '/Account'
      fullPath: '/Account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/terms': {
      id: '/policy/terms'
      path: '/policy/terms'
      fullPath: '/policy/terms'
      preLoaderRoute: typeof PolicyTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/shipping': {
      id: '/policy/shipping'
      path: '/policy/shipping'
      fullPath: '/policy/shipping'
      preLoaderRoute: typeof PolicyShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/returns': {
      id: '/policy/returns'
      path: '/policy/returns'
      fullPath: '/policy/returns'
      preLoaderRoute: typeof PolicyReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/about': {
      id: '/policy/about'
      path: '/policy/about'
      fullPath: '/policy/about'
      preLoaderRoute: typeof PolicyAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/$slug': {
      id: '/policy/$slug'
      path: '/policy/$slug'
      fullPath: '/policy/$slug'
      preLoaderRoute: typeof PolicySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ComingSoonRoute: ComingSoonRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRoute,
  SoonRoute: SoonRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoresRoute: StoresRoute,
  SuccessRoute: SuccessRoute,
  TrackOrderRoute: TrackOrderRoute,
  WishlistRoute: WishlistRoute,
  CategorySlugRoute: CategorySlugRoute,
  PolicySlugRoute: PolicySlugRoute,
  PolicyAboutRoute: PolicyAboutRoute,
  PolicyReturnsRoute: PolicyReturnsRoute,
  PolicyShippingRoute: PolicyShippingRoute,
  PolicyTermsRoute: PolicyTermsRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
